# Generated by Django 5.2.6 on 2025-09-11 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_expense'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='name',
            new_name='expense_name',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='date',
        ),
    ]
